name: "Dev - Terraform Automation"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Select manual action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

concurrency:
  group: terraform-dev
  cancel-in-progress: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TARGET_DIR: "live/dev"
  TF_VERSION: "1.14.6"

jobs:

  terraform_plan:
    name: "Terraform Plan - Dev"
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' ||
      github.event.inputs.terraform_action == 'plan' ||
      github.event.inputs.terraform_action == 'apply'

    defaults:
      run:
        working-directory: ${{ env.TARGET_DIR }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Profile
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --profile me
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --profile me
          aws configure set region us-east-1 --profile me

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Save Plan Artifact
        uses: actions/upload-artifact@v5
        with:
          name: tfplan-dev
          path: ${{ env.TARGET_DIR }}/tfplan


  terraform_apply:
    name: "Terraform Apply - Dev"
    runs-on: ubuntu-latest
    needs: terraform_plan

    environment: development

    if: |
      github.event_name == 'push' ||
      github.event.inputs.terraform_action == 'apply'

    defaults:
      run:
        working-directory: ${{ env.TARGET_DIR }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Profile
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --profile me
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --profile me
          aws configure set region us-east-1 --profile me

      - name: Terraform Init
        run: terraform init

      - name: Download Plan Artifact
        uses: actions/download-artifact@v5
        with:
          name: tfplan-dev
          path: ${{ env.TARGET_DIR }}

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan

      - name: Clean Up Plan Artifact
        uses: geekyeggo/delete-artifact@v6
        if: success()
        with:
          name: tfplan-dev


  terraform_destroy:
    name: "Terraform Destroy - Dev"
    runs-on: ubuntu-latest

    environment: development

    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.terraform_action == 'destroy'

    defaults:
      run:
        working-directory: ${{ env.TARGET_DIR }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Profile
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --profile me
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --profile me
          aws configure set region us-east-1 --profile me

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -input=false -auto-approve
